---
  - hosts: localhost
    connection: local
    become: true
    pre_tasks:
      - name: update repositories
        yum:
          update_cache: yes
          changed_when: False
        when: ansible_distribution == "CentOS"
      - name: update repositories
        apt:
          update_cache: yes
          changed_when: False
        when: ansible_distribution == "Ubuntu"

    tasks:
      - include: tasks/packages.yml
