---
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: install updates (CentOS)
    yum:
      name: htop
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install updates (Ubuntu)
    apt:
      name: htop
      state: latest
    when: ansible_distribution == "Ubuntu"
