---
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install htop package (CentOS)
    yum:
      name:
        - htop
        - mc
        - tmux
      state: latest
    when: ansible_distribution == "CentOS"
  - name: Install htop package (Ubuntu)
    apt:
      name: 
        - htop
        - mc
        - tmux
      state: latest
    when: ansible_distribution == "Ubuntu"
