---
- hosts: all
  become: true
  tasks:
  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
      name: htop
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
      name: htop
      state: latest
    when: ansible_distribution == "Ubuntu"
