- name: Install htop package (CentOS)
  yum:
    name:
      - htop
      - mc
      - xterm
    state: latest
  when: ansible_distribution == "CentOS"
- name: Install htop package (Ubuntu)
  apt:
    name: 
      - htop
      - mc
      - xterm
    state: latest
  when: ansible_distribution == "Ubuntu"
